### ISSUE TITLE
Feature Improvements

### ISSUE THREAD

**Issue by rayliverified** [webianks/PopupBubble#10]
This is a great library but there are UI quirks and extensible functionality that I would like to add. Here is a list of what I feel is needed. 

- [ ] isActivated() method. Get if PopupBubble is active. Currently, there is no way to know if a popup bubble exists and recreating a popup bubble reruns the animation. 
- [ ] Disable hide when scroll up. Scrolling up hides popup bubble. Should be option to disable as this behavior is sometimes wonky. 

I'll be working on these changes in my fork and hopefully have a PR ready at the end of this weekend.

**Comment by rayliverified** [comment]
Will be getting to these improvements hopefully soon :hourglass:

**Comment by nichnet** [comment]
hi, just wondering if this feature has been added (about choosing whether or not the popup vanishes on scroll up)? every time my users scrolls up (even slightly) the popup vanishes. If you could put a condition [here](https://github.com/webianks/PopupBubble/blob/master/popup-bubble/src/main/java/com/webianks/library/RecyclerViewListener.java#L36) (around everything already inside that method) that if true the vanishing on scroll up is wanted and if false just dont do anything inside that method. that would be great! :+1:

**Comment by rayliverified** [comment]
@syaak I'm currently not using this library in any active projects. When I do integrate this library, I'll get around to making the enhancements.

**Comment by rayliverified** [comment]
Closing for now.
