### ISSUE TITLE
URGENT: Improper Library Manifest

### ISSUE THREAD

**Issue by rayliverified** [webianks/PopupBubble#13]
The library manifest should not have a application declaration. This causes errors in Android's preview rendering such as NoClassFoundException and Class Could Not Be Instantiated for support views. Removing declaration allows popup to be displayed correctly and Android previews to work properly. 

Fixed in PR #12

**Comment by webianks** [comment]
I don't how that was added but thanks anyways.

**Comment by rayliverified** [comment]
Thank you for making this library!
