### ISSUE TITLE
 No resource identifier found for attribute 'pb_backgroundColor' in package 'my.package'

### ISSUE THREAD

**Issue by rakshitsoni02** [webianks/PopupBubble#5]
custom attributes not resolving i am adding 
    xmlns:app="http://schemas.android.com/apk/res-auto"

as resolver , please suggest if i am doing something wrong.

**Comment by webianks** [comment]
You were not doing wrong. I was doing wrong the library version was not updated. Please use "1.0.3" in dependency to resolve that issue.

**Comment by rakshitsoni02** [comment]
@webianks thanks man now works.. cheers
